'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class BUILDINGPERMIT_OBO

    '''<summary>
    '''_oLabelSnackbar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLabelSnackbar As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oLabelSnackbargreen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLabelSnackbargreen As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oTxtLName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtLName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtFName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtFName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtMName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtMName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtFormofOwnership control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtFormofOwnership As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''_oTxtTINNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtTINNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtCTCNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtCTCNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtCTCDateIssued control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtCTCDateIssued As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl

    '''<summary>
    '''_oTxtCTCPlaceIssued control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtCTCPlaceIssued As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtNoStrt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtNoStrt As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtBrgy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtBrgy As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtCity As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtProvince control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtProvince As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtZIPCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtZIPCode As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtEmail As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtTelNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtTelNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtLotNoLOC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtLotNoLOC As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtBlkNoLOC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtBlkNoLOC As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtStreetLOC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtStreetLOC As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtBrgyLOC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtBrgyLOC As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtCityLOC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtCityLOC As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtTCTNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtTCTNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtTDN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtTDN As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtTotArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtTotArea As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oGvUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oGvUpload As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''btnDownloadAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDownloadAll As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''_oCbFindings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oCbFindings As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''_oTxtComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtComments As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''_oBtnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oBtnSave As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''_obtnNotifyClient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _obtnNotifyClient As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''div1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ltEmbed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltEmbed As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''_oTxtRemarks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtRemarks As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''_obtnConfirmStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _obtnConfirmStatus As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdnName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnName As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnType As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnData As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnaction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnaction As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnTransID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnTransID As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnReqCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnReqCode As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnAppNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnAppNo As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnseqid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnseqid As Global.System.Web.UI.HtmlControls.HtmlInputHidden
End Class
