'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class BUILDINGPERMIT_APPLICATION

    '''<summary>
    '''_oLabelSnackbar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLabelSnackbar As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''_oLabelSnackbargreen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oLabelSnackbargreen As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Div_AppInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div_AppInfo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''_oTxtLName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtLName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtFName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtFName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtMName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtMName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtFormofOwnership control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtFormofOwnership As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''_oTxtTINNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtTINNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtCTCNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtCTCNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtCTCDateIssued control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtCTCDateIssued As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl

    '''<summary>
    '''_oTxtCTCPlaceIssued control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtCTCPlaceIssued As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtNoStrt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtNoStrt As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtBrgy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtBrgy As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtCity As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtProvince control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtProvince As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtZIPCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtZIPCode As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtUserID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtUserID As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtEmail As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtTelNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtTelNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtLotNoLOC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtLotNoLOC As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtBlkNoLOC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtBlkNoLOC As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtStreetLOC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtStreetLOC As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtBrgyLOC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtBrgyLOC As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtCityLOC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtCityLOC As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtTCTNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtTCTNo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtTDN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtTDN As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oTxtTotArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtTotArea As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_oBtnSaveAppInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oBtnSaveAppInfo As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''_oBtnSaveApplication control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oBtnSaveApplication As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''_oBtnEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oBtnEdit As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''UPUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UPUpload As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''_oGvUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oGvUpload As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''_oBtnUploadRequirements control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oBtnUploadRequirements As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''_oBtnSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oBtnSubmit As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''_oTxtHdnEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _oTxtHdnEdit As Global.System.Web.UI.HtmlControls.HtmlInputHidden
End Class
